### ISSUE TITLE
iCal file downloads as empty UNKNOWN file

### ISSUE THREAD

**Issue by Van-Halen** [ayesham/addtocalendar#1]
Great script, but i could not get it to work on Safari/Mac.

I modified the code a bit on line 83 of addToCalendarNative.js

`        return 'addtocalendar.php?data=BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nSEQUENCE:0\n'`

and created a small php file (addtocalendar.php):

`$ical = $_GET["data"];`
`header('Content-type: text/calendar; charset=utf-8');`
`header('Content-Disposition: inline; filename=calendar.ics');`
`echo $ical;`
`exit;`

Not safe for production, since there's no security check for who uses the .php file

**Comment by ayesham** [comment]
Just to get better understanding, you want the php file to process the ics file?

**Comment by Van-Halen** [comment]
No it does not have to be a php file, but the file needs to be downloaded with the right file content-type headers. At least for me, your script did not work when i downloaded the .ical file, i got a UNKNOWN empty file.

**Comment by Van-Halen** [comment]
personal note, if you extend this script, you could create a alternative service for https://www.addevent.com or http://addtocalendar.com which i currently use for production websites, but i don't like that they add their website address to the ical event.

**Comment by ayesham** [comment]
Unfortunately on safari there is no way to name this file correctly on the client side, not even with [FileSaver](https://github.com/eligrey/FileSaver.js/).

I googled like anything and this is a known issue. Anyway, I added a fix with `php` as you suggested. We just need it to be an attachment and it will work. Try it and let me know if this works for you.

If you are testing on localhost you would want to enable this mime-type in your mime module with the following line, and restart apache:
`AddType text/calendar .ics`

Fixed via f57a4a7.

**Comment by ayesham** [comment]
Before I built this script I looked at every solution available out there including https://www.addevent.com and http://addtocalendar.com. I am not a big fan of ugly and loaded libraries to do simple things, so I just decided to do this in native JS with data attribute support. I also didn't want to pay to https://www.addevent.com/ to have this functionality. I can't remember why in addition to the ugly globally spaced code, I didn't choose https://www.addevent.com/.

Anyway hope you find this script much easier to use.

>personal note, if you extend this script, you could create a alternative service for https://www.addevent.com or http://addtocalendar.com which i currently use for production websites, but i don't like that they add their website address to the ical event.
